# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/yc185_cardio_capstone/weekly_progress/week7/vivado/FIR/project_3_FIR_IP_xdc_test2/project_3_FIR_IP_xdc_test2.srcs/sources_1/ip/fir_compiler_0_1/fir_compiler_0.xci
# IP: The module: 'fir_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/yc185_cardio_capstone/weekly_progress/week7/vivado/FIR/project_3_FIR_IP_xdc_test2/project_3_FIR_IP_xdc_test2.gen/sources_1/ip/fir_compiler_0_1/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/yc185_cardio_capstone/weekly_progress/week7/vivado/FIR/project_3_FIR_IP_xdc_test2/project_3_FIR_IP_xdc_test2.gen/sources_1/ip/fir_compiler_0_1/fir_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/yc185_cardio_capstone/weekly_progress/week7/vivado/FIR/project_3_FIR_IP_xdc_test2/project_3_FIR_IP_xdc_test2.srcs/sources_1/ip/fir_compiler_0_1/fir_compiler_0.xci
# IP: The module: 'fir_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/yc185_cardio_capstone/weekly_progress/week7/vivado/FIR/project_3_FIR_IP_xdc_test2/project_3_FIR_IP_xdc_test2.gen/sources_1/ip/fir_compiler_0_1/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/yc185_cardio_capstone/weekly_progress/week7/vivado/FIR/project_3_FIR_IP_xdc_test2/project_3_FIR_IP_xdc_test2.gen/sources_1/ip/fir_compiler_0_1/fir_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
